apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment-2-updates
  name: nginx-deployment-2-updates
  namespace: giropops
spec:
  replicas: 50
  selector:
    matchLabels:
      app: nginx-deployment-2-updates
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment-2-updates
    spec:
      containers:
      - image: nginx:1.14.0
        name: nginx
        resources: {}
status: {}
