apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment-2-updates
  name: nginx-deployment-2-updates
  namespace: giropops
spec:
  replicas: 50
  selector:
    matchLabels:
      app: nginx-deployment-2-updates
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 #Pode ter até X pods a mais do que eu pedi no arquivo
      maxUnavailable: 1 #Vai atualizar de X em X pods
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment-2-updates
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources: {}
status: {}
