apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserver01
  name: webserver02
spec:
  containers:
  - image: nginx
    name: webserver01
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
