apiVersion: v1
kind: Pod
metadata:
  labels:
    run: licaodecasa
  name: licaodecasa
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /tmp/nginx-volume
      name: nginx-volume
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - image: alpine
    name: alpine-container
    volumeMounts:
    - mountPath: /tmp/alpine-volume
      name: alpine-volume
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: "0.2"
        memory: "32Mi"
      requests:
        cpu: "0.1"
        memory: "16Mi"
  - image: ubuntu
    name: ubuntu-container
    volumeMounts:
    - mountPath: /tmp/ubuntu-volume
      name: ubuntu-volume
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: "0.2"
        memory: "64Mi"
      requests:
        cpu: "0.1"
        memory: "32Mi"
  - image: redis
    name: redis-container
    volumeMounts:
    - mountPath: /tmp/redis-volume
      name: redis-volume
    resources:
      limits:
        cpu: "0.3"
        memory: "128Mi"
      requests:
        cpu: "0.2"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nginx-volume
    emptyDir:
      sizeLimit: 512Mi
  - name: alpine-volume
    emptyDir:
      sizeLimit: 256Mi
  - name: ubuntu-volume
    emptyDir:
      sizeLimit: 128Mi
  - name: redis-volume
    emptyDir:
      sizeLimit: 64Mi